services:
  sempl-it-inference:
    container_name: 'sempl-it-inference'
    image: 'vllm/vllm-openai:v0.8.5.post1'
    restart: 'unless-stopped'
    ports:
      - '8000:8000'
    volumes:
      - '~/.cache/huggingface:/root/.cache/huggingface'
    environment:
      - 'VLLM_API_KEY=${VLLM_API_KEY:-123456789}'
    command: ["--model=abhishekchohan/Qwen3-4B-AWQ",
              "--quantization=awq_marlin",
              "--load-format=auto",
              "--gpu-memory-utilization=0.95",
              "--max-model-len=6144",
              "--max-seq_len-to-capture=6144",
              "--enable-prefix-caching",
              "--enable-lora",
              "--max-loras=9",
              "--max_lora_rank=64",
              "--lora-modules",
              "{\"name\":\"proofreading\",\"path\":\"VerbACxSS/sempl-it-v3-proofreading-awq\"}",
              "{\"name\":\"lex\",\"path\":\"VerbACxSS/sempl-it-v3-lex-awq\"}",
              "{\"name\":\"connectives\",\"path\":\"VerbACxSS/sempl-it-v3-connectives-awq\"}",
              "{\"name\":\"expressions\",\"path\":\"VerbACxSS/sempl-it-v3-expressions-awq\"}",
              "{\"name\":\"sentence_splitter\",\"path\":\"VerbACxSS/sempl-it-v3-sentence-splitter-awq\"}",
              "{\"name\":\"nominalizations\",\"path\":\"VerbACxSS/sempl-it-v3-nominalizations-awq\"}",
              "{\"name\":\"verbs\",\"path\":\"VerbACxSS/sempl-it-v3-verbs-awq\"}",
              "{\"name\":\"sentence_reorganizer\",\"path\":\"VerbACxSS/sempl-it-v3-sentence-reorganizer-awq\"}",
              "{\"name\":\"explain\",\"path\":\"VerbACxSS/sempl-it-v3-explain-awq\"}"]
    ipc: host
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]